### PR TITLE
Coverage tracking and graphical representation

### PR DESCRIPTION
**Pull request by timleavitt**
I've had a bit of free time and was curious (this is a really interesting idea!), so I've added a few more pieces you can cobble in to your vision for code coverage. These are, in some sense, the trickier parts.

At a basic level: import all the code here, then:
Do ##class(UnitTest.Main).Run(2)

The above method will simulate running a unit test with code coverage tracked for a few particular classes. The code coverage is tracked in the .int code but also mapped back to .cls.

You can then also go to utcov.UI.SimpleResultViewer.cls in your namespace's default web application (typically /csp/<namespace>/ - i.e., /csp/utcov/utcov.UI.SimpleResultViewer.cls for me) to show the code coverage results, filterable by test run / test class / test method.

In terms of using this, you can call in to utcov.Manager with lists of classes similarly to how UnitTest.Main::Run does. The queries in SimpleResultViewer may be useful for drilling down through the results.

There are still a few major challenges I see:
1. Determining if a particular line of code can actually be executed (and therefore if lack of coverage should be a red flag). Some things like comments are obvious. Other things like "Try {" don't ever show up as executed. This really requires COS parsing. This isn't implemented in the pull request, but there's a property for it in the persistent class and 
2. Holes in the .int -> .cls mapping - what we have from %Studio.Debugger is pretty good, but isn't perfect, and would be very difficult to extend.
3. Measuring coverage of generated code and code-generating code. (One option would be to compile classes that do code generation as part of the unit tests, assuming the unit tests use helper classes that are unit test-specific and are intended to exercise all paths of the code generator.)

The persistent class could probably be broken down a bit as well. It's currently all one big table with lots of duplicated data, but doesn't need to be; performance might improve if it's split out into several.

The viewer uses Zen, which was great for throwing it together really quickly. REST APIs providing similar information would be nice in the longer run, especially from the perspective of decoupling UI and back-end if the table structure is to change.

Enjoy!
Tim

### CODE REVIEW

**Comment by timleavitt** [comment]
@fge - thoughts/questions?

**Comment by fge** [comment]
@timleavitt a lot, obviously :)

The first of it however: did you develop with Atelier?

**Comment by timleavitt** [comment]
Yes, almost entirely. Lack of SASchema support for Zen was the biggest headache, so I went back to Studio for just a bit for that. The folder structure was a bit weird and required some extra work to adhere to, but I didn't want to change that on you.

(I've been developing in Studio for 7 years and I'm not that much of an Eclipse expert yet. Maybe there are good ways to deal with this; I don't know.)

**Comment by fge** [comment]
Hmm, OK. I'll merge it as is.

The goal, ultimately, is that this data be usable "as is" from another project of mine, which is https://github.com/litesolutions/cache-import; the plan for now is as follows:
- a configuration is sent, as JSON, to the Caché server;
- from this configuration, the server is able to compute what classes are needed, and among these, which are test classes;
- collect those test classes, run them with coverage, and send back to the caller a single (reference to a) JSON file containing all the informations.

And yes, that is for [Caché Quality](https://demo.cachequality.com).

In any event, you went much further than I did so I'll merge it as is, and read, and learn, and read, and learn again.

I was stopped at the JSON side of things... And I have to update the README. Anyway, if the project can do both "Studio rendering" and what I have in mind via a common interface then that's a win in any case.

**Comment by timleavitt** [comment]
Great! I think this will be directly useful toward your end goal.

If you're stuck on anything particular JSON/REST related in Caché, I'm sure you could get some pointers on the Developer Community. The modern approaches to that are new territory for a lot of people, and I'm sure it would be a beneficial discussion. (Thanks for your involvement there so far, by the way.)

**Pull request merged**
